containerSecurityContext:
  enabled: true
  runAsUser: 1002
podSecurityContext:
  enabled: true
  fsGroup: 1002
containerPorts:
  http: 1235
service:
  type: LoadBalancer
  ports:
    http: 80
wavefront:
  enabled: true
  wavefront:
    url: https://YOUR_CLUSTER.wavefront.com
    token: YOUR_API_TOKEN 
  proxy:
    enabled: true
    port: 2878