apiVersion: v2
appVersion: 7.1.3
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
  - condition: kafka.enabled
    name: kafka
    repository: https://charts.bitnami.com/bitnami
    version: 18.x.x
description: Confluent Schema Registry provides a RESTful interface by adding a serving layer for your metadata on top of Kafka. It expands Kafka enabling support for Apache Avro, JSON, and Protobuf schemas.
engine: gotpl
home: https://confluent.io/
icon: https://bitnami.com/assets/stacks/schema-registry-stac/img/schema-registry-stack-220x234.png
keywords:
  - schema-registry
  - confluent
  - kafka
  - zookeeper
  - streaming
maintainers:
  - name: Bitnami
    url: https://github.com/bitnami/charts
name: schema-registry
sources:
  - https://github.com/bitnami/bitnami-docker-schema-registry
version: 4.0.0
