# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  category: Wiki
  licenses: Apache-2.0
  images: |
    - name: apache-exporter
      image: docker.io/bitnami/apache-exporter:1.0.6-debian-12-r8
    - name: dokuwiki
      image: docker.io/bitnami/dokuwiki:20240206.1.0-debian-12-r0
    - name: os-shell
      image: docker.io/bitnami/os-shell:12-debian-12-r16
apiVersion: v2
appVersion: 20240206.1.0
dependencies:
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  tags:
  - bitnami-common
  version: 2.x.x
description: DokuWiki is a standards-compliant wiki optimized for creating documentation. Designed to be simple to use for small organizations, it stores all data in plain text files so no database is required.
home: https://bitnami.com
icon: https://bitnami.com/assets/stacks/dokuwiki/img/dokuwiki-stack-220x234.png
keywords:
- dokuwiki
- wiki
- http
- web
- application
- php
maintainers:
- name: VMware, Inc.
  url: https://github.com/bitnami/charts
name: dokuwiki
sources:
- https://github.com/bitnami/charts/tree/main/bitnami/dokuwiki
version: 15.0.0
