{{- /*
Copyright VMware, Inc.
SPDX-License-Identifier: APACHE-2.0
*/}}

apiVersion: v1
kind: Service
metadata:
  name:  {{ printf "%s-headless" (include "flink.taskmanager.fullname" .) | trunc 63 | trimSuffix "-" }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/part-of: flink
    app.kubernetes.io/component: taskmanager
  {{- if or .Values.taskmanager.service.annotations .Values.commonAnnotations }}
  {{- $annotations := include "common.tplvalues.merge" ( dict "values" ( list .Values.taskmanager.service.annotations .Values.commonAnnotations ) "context" . ) }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" $annotations "context" $) | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: data
      port: {{ .Values.taskmanager.service.ports.data }}
      targetPort: {{ .Values.taskmanager.containerPorts.data }}
      {{- if and (or (eq .Values.taskmanager.service.type "NodePort") (eq .Values.taskmanager.service.type "LoadBalancer")) (not (empty .Values.taskmanager.service.nodePorts.data)) }}
      nodePort: {{ .Values.taskmanager.service.nodePorts.data }}
      {{- else if eq .Values.taskmanager.service.type "ClusterIP" }}
      nodePort: null
      {{- end }}
    - name: tcp-rpc
      port: {{ .Values.taskmanager.service.ports.rpc }}
      targetPort: {{ .Values.taskmanager.containerPorts.rpc }}
      {{- if and (or (eq .Values.taskmanager.service.type "NodePort") (eq .Values.taskmanager.service.type "LoadBalancer")) (not (empty .Values.taskmanager.service.nodePorts.rpc)) }}
      nodePort: {{ .Values.taskmanager.service.nodePorts.rpc }}
      {{- else if eq .Values.taskmanager.service.type "ClusterIP" }}
      nodePort: null
      {{- end }}
    {{- if .Values.taskmanager.service.extraPorts }}
    {{- include "common.tplvalues.render" (dict "value" .Values.taskmanager.service.extraPorts "context" $) | nindent 4 }}
    {{- end }}
  {{- $podLabels := include "common.tplvalues.merge" ( dict "values" ( list .Values.taskmanager.podLabels .Values.commonLabels ) "context" . ) }}
  selector: {{- include "common.labels.matchLabels" ( dict "customLabels" $podLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/part-of: flink
    app.kubernetes.io/component: taskmanager
