# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  category: Infrastructure
  licenses: Apache-2.0
  images: |
    - name: fluxcd-helm-controller
      image: docker.io/bitnami/fluxcd-helm-controller:0.37.4-debian-12-r6
    - name: fluxcd-image-automation-controller
      image: docker.io/bitnami/fluxcd-image-automation-controller:0.37.1-debian-12-r6
    - name: fluxcd-image-reflector-controller
      image: docker.io/bitnami/fluxcd-image-reflector-controller:0.31.2-debian-12-r6
    - name: fluxcd-kustomize-controller
      image: docker.io/bitnami/fluxcd-kustomize-controller:1.2.2-debian-12-r6
    - name: fluxcd-notification-controller
      image: docker.io/bitnami/fluxcd-notification-controller:1.2.4-debian-12-r6
    - name: fluxcd-source-controller
      image: docker.io/bitnami/fluxcd-source-controller:1.2.4-debian-12-r7
    - name: os-shell
      image: docker.io/bitnami/os-shell:12-debian-12-r16
apiVersion: v2
appVersion: 1.2.4
dependencies:
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  tags:
  - bitnami-common
  version: 2.x.x
description: Source Controller is a component of Flux. Flux is a tool for keeping Kubernetes clusters in sync with sources of configuration.
home: https://bitnami.com
icon: https://bitnami.com/assets/stacks/fluxcd-kustomize-controller/img/fluxcd-kustomize-controller-stack-220x234.png
keywords:
- deployment
- gitops
- cd
- continuous-delivery
- helm
- kustomize
maintainers:
- name: VMware, Inc.
  url: https://github.com/bitnami/charts
name: flux
sources:
- https://github.com/bitnami/charts/tree/main/bitnami/flux
version: 2.0.1
